version: '3.4'

services:
  backend:
    platform: linux/arm64
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: url-shortener:dev
    command: npm run debug
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=url_shortener
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - URL_REDIRECT_DOMAIN=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume-dev:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - redis-volume-dev:/data

volumes:
  postgres-volume-dev:
  redis-volume-dev: