version: '3.4'

services:
  backend:
    build:
      context: .
      target: test
      dockerfile: Dockerfile
    image: url-shortener:test
    command: npm test
    environment:
      - NODE_ENV=test
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=url_shortener_test
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - BASE_DOMAIN=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=url_shortener_test
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume-test:/var/lib/postgresql/data

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis-volume-test:/data

volumes:
  postgres-volume-test:
  redis-volume-test:
