version: '3.4'

services:
  backend:
    volumes:
      - ./:/opt/node_app
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      - /opt/node_app/node_modules
    environment:
      - ALLOWED_ORIGINS=http://localhost:8080
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13.1
    volumes:
      - ./src/db/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
  redis:
    image: redis:6.0
    volumes:
      - redis-volume:/data

volumes:
  redis-volume:
  postgres-volume: