name: Build and deploy
on:
  workflow_run:
    workflows: [Test and build]
    types:
      - completed
    branches:
      - master
env:
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  APP_NAME: url_shortener
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      DOCKER_BUILD_PUSH_PASSWORD: ${{ secrets.DOCKER_BUILD_DEPLOY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        id: build_image
        run: docker build -t "$IMAGE_REGISTRY/$APP_NAME:$GITHUB_SHA" --target release .
      - name: Log in to github container registry
        id: login_registry
        run: echo $DOCKER_BUILD_PUSH_PASSWORD | docker login ghcr.io -u $REGISTRY_USER --password-stdin
      - name: Push to registry
        id: push_image
        run: docker push "$IMAGE_REGISTRY/$APP_NAME:$GITHUB_SHA"
      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push_image.outputs) }}"
  health_check:
    runs-on: ubuntu-latest
    needs: [build_and_upload]
    steps:
      - name: Check whether URL shortener is up
        id: health_check
        run: |
          curl $SSH_HOST/healthz
  notify_unsuccessful_health_check:
    runs-on: ubuntu-latest
    needs: [health_check]
    if: ${{ failure() }}
    steps:
      - name: Send slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          now=$(date +%Y-%m-%dT%H:%M:%S)
          payload=$(echo "{\"text\":\"URL shortener backend: Health check for $SSH_HOST/healthz failed at <DATE>\"}" | sed "s~<DATE>~$now~")
          curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK
          exit 1
  deploy:
    runs-on: ubuntu-latest
    needs: [health_check]
    steps:
      - uses: actions/checkout@v3        
      - name: Configure SSH
        id: ssh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/url_shortener_rsa
          chmod 600 ~/.ssh/url_shortener_rsa
          SSH_HOST_IP=$(nslookup $SSH_HOST | tail -n 2 | head -n 1 | cut -d ' ' -f 2)
          echo "host name: $SSH_HOST, host ip address: $SSH_HOST_IP"
          cat << EOF >> ~/.ssh/config
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/url_shortener_rsa
            StrictHostKeyChecking no
          EOF
      - name: SSH into server, pull image, run container
        id: deploy
        env:
          NODE_ENV: production
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
          BASE_DOMAIN: ${{ secrets.BASE_DOMAIN }}
          DOCKER_PULL_PASSWORD: ${{ secrets.DOCKER_PULL_TOKEN }}
        run: |
          ssh production << EOF
          echo "Logging into container registry"
          echo $DOCKER_PULL_PASSWORD | docker login ghcr.io -u $REGISTRY_USER --password-stdin

          echo "Pulling image"
          docker pull "$IMAGE_REGISTRY/$APP_NAME:$GITHUB_SHA"

          echo "Stopping existing container"
          docker stop url_shortener && docker rm url_shortener

          echo "Starting new container"
          docker run --name url_shortener -p 3000:3000 --network host -e NODE_ENV=$NODE_ENV -e POSTGRES_HOST=$POSTGRES_HOST \
          -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -e POSTGRES_DB=$POSTGRES_DB \
          -e REDIS_URL=$REDIS_URL -e BASE_DOMAIN=$BASE_DOMAIN -e ALLOWED_ORIGINS=$ALLOWED_ORIGINS \
          -d "$IMAGE_REGISTRY/$APP_NAME:$GITHUB_SHA"

          sleep 5
          docker ps
          EOF
  notify_unsuccessful:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: ${{ failure() }}
    steps:
      - name: Send slack notification unsuccessful run    
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          now=$(date +%Y-%m-%dT%H:%M:%S)
          payload=$(echo "{\"text\":\"URL shortener backend: Deployment failed at <DATE>\"}" | sed "s~<DATE>~$now~")
          curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK
  notify_successful:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Send slack notification successful run
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          now=$(date +%Y-%m-%dT%H:%M:%S)
          payload=$(echo "{\"text\":\"URL shortener backend: Deployment succeeded at <DATE>\"}" | sed "s~<DATE>~$now~")
          curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK

      