name: Test workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests with docker compose
        run: |
          ./docker-compose.sh build test
          ./docker-compose.sh up test --exit-code-from backend
          ./docker-compose.sh down test
  build_and_push_image:
    runs-on: ubuntu-latest
    env:
      APP_NAME: url_shortener
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        id: build-image
        run: docker build -t "$APP_NAME:$GITHUB_SHA" .
      - name: Login to registry
        id: login-registry
        run: echo $DOCKER_BUILD_DEPLOY_TOKEN | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Push to registry
        id: push-image
        run: docker push "ghcr.io/${{ github.repository_owner }}/$APP_NAME:$GITHUB_SHA"