name: Test workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests with docker compose
        run: |
          ./docker-compose.sh build test
          ./docker-compose.sh up test --exit-code-from backend
          ./docker-compose.sh down test
  build_and_push_image:
    runs-on: ubuntu-latest
    env:
      APP_NAME: url_shortener
    steps:
      - name: Export environment variables
        run: |
          export IMAGE_NAME="$APP_NAME:$GITHUB_SHA"
          export IMAGE_REGISTRY="ghcr.io/${{ github.repository_owner }}"
          export IMAGE_ID="$IMAGE_REGISTRY/$IMAGE_NAME"
      - name: Build docker image
        id: build-image
        run: docker build -t $IMAGE_NAME .
      - name: Login to registry
        id: login-registry
        run: echo $DOCKER_BUILD_DEPLOY_TOKEN | docker login ghcr.io -u hanchiang --password-stdin
      - name: Push to registry
        id: push-image
        run: docker push $IMAGE_ID