name: Test and build
on:
  push:
    branches:
      - feature/*
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests with docker compose
        run: |
          ./docker-compose.sh test build 
          ./docker-compose.sh test up --exit-code-from backend
          ./docker-compose.sh test down
  build_image:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ success() }}
    env:
      APP_NAME: url_shortener
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
      REGISTRY_USER: ${{ github.actor }}
      DOCKER_BUILD_PUSH_PASSWORD: ${{ secrets.DOCKER_BUILD_DEPLOY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        id: build_image
        run: docker build -t "$IMAGE_REGISTRY/$APP_NAME:$GITHUB_SHA" --target release .
      - name: Log in to github container registry
        id: login_registry
        run: echo $DOCKER_BUILD_PUSH_PASSWORD | docker login ghcr.io -u $REGISTRY_USER --password-stdin
      - name: Push to registry
        id: push_image
        run: docker push "$IMAGE_REGISTRY/$APP_NAME:$GITHUB_SHA"
      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push_image.outputs) }}"